version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - cd cdk
      - npm ci
      - aws secretsmanager get-secret-value --secret-id ${STACK_CONFIG}/${ENV} | jq -r '.SecretString' > environments/${ENV}.config.json
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npx cdk synth HBTechnicalSupportServcieStack -o dist

artifacts:
  base-directory: cdk/dist
  files:
    - 'HBTechnicalSupportServcieStack.template.json'
  discard-paths: no